name: "POSSE photos to Mastodon with GitHub Action"
on:
  schedule:
    # At 12:37 (UTC) on every day-of-week from Monday through Friday.
    # https://crontab.guru/#37_12_*_*_1-5
    - cron: "37 12 * * 1-5"
  workflow_dispatch:

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ“¥
        uses: actions/checkout@v3

      - name: POSSE photos to Mastodon ðŸ¦£
        uses: nhoizey/github-action-jsonfeed-to-mastodon@v1
        with:
          feedUrl: "https://nicolas-hoizey.photo/feeds/mastodon/photos.json"
          mastodonInstance: ${{ secrets.MASTODON_INSTANCE }}
          mastodonToken: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cacheFile: "posse-mastodon-photo.json"
          cacheTimestampFile: "posse-mastodon-photo-timestamp.json"
          globalDelayToots: 1200 # 20 hours

      - name: Pull any changes from Git ðŸ“¥
        run: git pull

      - name: Commit and push ðŸ“¤
        uses: stefanzweifel/git-auto-commit-action@v4
