name: "ğŸ“¸Â â†’Â ğŸ˜ POSSE photos to Mastodon"
on:
  schedule:
    # https://crontab.guru/#17_12_*_*_*
    - cron: "17 12 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ“¥
        uses: actions/checkout@v3

      - name: POSSE photos to Mastodon ğŸ¦£
        uses: nhoizey/github-action-jsonfeed-to-mastodon@v1
        with:
          feedUrl: "https://nicolas-hoizey.photo/feeds/mastodon/photos.json"
          mastodonInstance: ${{ secrets.MASTODON_INSTANCE }}
          mastodonToken: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cacheFile: "posse-mastodon-photo.json"
          cacheTimestampFile: "posse-mastodon-photo-timestamp.json"
          globalDelayToots: 1200 # 20 hours

      - name: Pull any changes from Git ğŸ“¥
        run: git pull

      - name: Commit and push ğŸ“¤
        uses: stefanzweifel/git-auto-commit-action@v4
